"""phase 3b invoice submission

Revision ID: 4b2787a3f61d
Revises: aa77c7b4ba79
Create Date: 2026-08-05 17:10:25.478923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2787a3f61d'
down_revision: Union[str, None] = 'aa77c7b4ba79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('item_code_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period_service_from', sa.Date(), nullable=False),
    sa.Column('period_service_to', sa.Date(), nullable=False),
    sa.Column('billing_milestone_id', sa.UUID(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('rate_variance_flag', sa.Boolean(), nullable=False),
    sa.Column('gst_mismatch_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('msme_alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='invoice_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['billing_milestone_id'], ['billing_milestones.id'], ),
    sa.ForeignKeyConstraint(['item_code_id'], ['item_codes.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE_PDF', 'GRN_SCN_ACK', 'WORK_COMPLETION_PROOF', 'TIMESHEET', 'MEASUREMENT_SHEET', 'PO_COPY', name='invoice_document_type'), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_documents')
    op.drop_table('invoices')
    # ### end Alembic commands ###
