"""phase 4a approval workflow

Revision ID: 506543d9852b
Revises: 4b2787a3f61d
Create Date: 2026-08-09 21:36:01.299409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506543d9852b'
down_revision: Union[str, None] = '4b2787a3f61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend the existing invoice_status enum with Phase 4A's approval-workflow statuses.
    # Autogenerate doesn't detect added labels on a Postgres ENUM type, so these are added
    # by hand. Safe inside this transaction (PG16) since none of these values are used by
    # any statement in this same migration.
    #
    # IMPORTANT: SQLAlchemy's Enum type (no values_callable configured, matching every
    # other enum column in this codebase) stores the Python enum MEMBER NAME as the
    # native Postgres label — e.g. purchase_order_status stores 'PENDING_APPROVAL', not
    # 'Pending_Approval'. These ADD VALUE labels must follow that same convention or a
    # later write of e.g. InvoiceStatus.L1_VERIFICATION fails with "invalid input value
    # for enum invoice_status" because SQLAlchemy sends the .name form ('L1_VERIFICATION')
    # but the type only knows the .value form ('L1_Verification'). Use .name-style values.
    for value in (
        'L1_VERIFICATION',
        'L2_REVIEW',
        'L3_APPROVAL',
        'L4_FINANCE_APPROVAL',
        'APPROVED_FOR_PAYMENT',
        'QUERY_RAISED',
        'RETURNED_TO_VENDOR',
        'REJECTED',
        'ON_HOLD',
    ):
        op.execute(f"ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doa_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('requires_l2', sa.Boolean(), nullable=False),
    sa.Column('requires_l3', sa.Boolean(), nullable=False),
    sa.Column('l1_role', sa.String(), nullable=False),
    sa.Column('l2_role', sa.String(), nullable=True),
    sa.Column('l3_role', sa.String(), nullable=True),
    sa.Column('l4_role', sa.String(), nullable=False),
    sa.Column('l1_tat_days', sa.Integer(), nullable=False),
    sa.Column('l2_tat_days', sa.Integer(), nullable=False),
    sa.Column('l3_tat_days', sa.Integer(), nullable=False),
    sa.Column('l4_tat_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_delegations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delegator_user_id', sa.UUID(), nullable=False),
    sa.Column('delegate_user_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegate_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', 'L4', name='approval_level'), nullable=False),
    sa.Column('assigned_role', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', 'RETURNED', 'QUERY_RAISED', 'SKIPPED', name='approval_stage_status'), nullable=False),
    sa.Column('action_taken_by', sa.UUID(), nullable=True),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('tat_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tat_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_taken_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('raised_at_level', sa.Enum('L1', 'L2', 'L3', 'L4', name='approval_level'), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESPONDED', name='query_status'), nullable=False),
    sa.Column('vendor_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('doa_matrix_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'doa_matrix', ['doa_matrix_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'doa_matrix_id')
    op.drop_table('invoice_queries')
    op.drop_table('invoice_approvals')
    op.drop_table('approval_delegations')
    op.drop_table('doa_matrix')
    # ### end Alembic commands ###

    # Note: the invoice_status enum values added in upgrade() are NOT removed here —
    # Postgres has no ALTER TYPE ... DROP VALUE; removing one requires rebuilding the type
    # (rename, create new, migrate column, drop old), which is unnecessary for local/dev
    # rollback of this phase and out of scope to script defensively.
