"""phase 1 vendor requests vendors item codes

Revision ID: 8a061045689a
Revises: 6d492fee9584
Create Date: 2026-07-20 18:08:13.017485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a061045689a'
down_revision: Union[str, None] = '6d492fee9584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('default_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_code_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('vendor_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('business_need', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('estimated_annual_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recommended_vendor_name', sa.String(), nullable=False),
    sa.Column('recommended_pan', sa.String(length=10), nullable=False),
    sa.Column('recommended_gstin', sa.String(length=15), nullable=True),
    sa.Column('financial_stability_ok', sa.Boolean(), nullable=False),
    sa.Column('technical_capability_ok', sa.Boolean(), nullable=False),
    sa.Column('compliance_status_ok', sa.Boolean(), nullable=False),
    sa.Column('blacklist_check_ok', sa.Boolean(), nullable=False),
    sa.Column('conflict_of_interest_declared', sa.Boolean(), nullable=False),
    sa.Column('references_provided', sa.Boolean(), nullable=False),
    sa.Column('msme_udyam_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACCOUNTS_REVIEW', 'PENDING_PARTNER_APPROVAL', 'APPROVED', 'REJECTED', 'ARCHIVED', name='vendor_request_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('accounts_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('accounts_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('partner_decided_by', sa.UUID(), nullable=True),
    sa.Column('partner_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounts_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_code', sa.String(), nullable=False),
    sa.Column('source_request_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('msme_status', sa.Boolean(), nullable=False),
    sa.Column('udyam_number', sa.String(), nullable=True),
    sa.Column('vendor_category', sa.Enum('PROFESSIONAL', 'SERVICE', 'GOODS_SUPPLIER', 'RECURRING', name='vendor_category'), nullable=False),
    sa.Column('tds_section', sa.String(), nullable=False),
    sa.Column('tds_section_overridden', sa.Boolean(), nullable=False),
    sa.Column('tds_section_override_reason', sa.Text(), nullable=True),
    sa.Column('bank_account_no', sa.String(), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_branch', sa.String(), nullable=False),
    sa.Column('cancelled_cheque_doc_url', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_request_id'], ['vendor_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pan'),
    sa.UniqueConstraint('source_request_id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_table('vendor_item_codes',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('item_code_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_code_id'], ['item_codes.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'item_code_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_item_codes')
    op.drop_table('vendors')
    op.drop_table('vendor_requests')
    op.drop_table('vendor_code_sequences')
    op.drop_table('item_codes')
    # ### end Alembic commands ###
