"""phase 2a agreements rate cards milestones amendments

Revision ID: 971b18378cdb
Revises: 8a061045689a
Create Date: 2026-07-21 14:41:15.978105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971b18378cdb'
down_revision: Union[str, None] = '8a061045689a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_code_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_number', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=False),
    sa.Column('supporting_document_url', sa.String(), nullable=False),
    sa.Column('billing_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'MILESTONE', 'AD_HOC', name='billing_frequency'), nullable=False),
    sa.Column('agreement_start_date', sa.Date(), nullable=False),
    sa.Column('agreement_end_date', sa.Date(), nullable=False),
    sa.Column('auto_renewal_flag', sa.Boolean(), nullable=False),
    sa.Column('po_requirement', sa.Enum('MANDATORY', 'OPTIONAL', 'NOT_REQUIRED', name='po_requirement'), nullable=False),
    sa.Column('credit_period_days', sa.Integer(), nullable=False),
    sa.Column('tds_section', sa.String(), nullable=False),
    sa.Column('tds_override_reason', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reverse_charge_flag', sa.Boolean(), nullable=False),
    sa.Column('approved_by_designation', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', name='agreement_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_number')
    )
    op.create_table('agreement_item_codes',
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('item_code_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['item_code_id'], ['item_codes.id'], ),
    sa.PrimaryKeyConstraint('agreement_id', 'item_code_id')
    )
    op.create_table('billing_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('percentage_of_contract_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('deliverables', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACHIEVED', 'INVOICED', name='milestone_status'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('item_code_id', sa.UUID(), nullable=False),
    sa.Column('pricing_type', sa.Enum('FIXED', 'PER_UNIT', 'MILESTONE', 'VOLUME_TIERED', name='pricing_type'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['item_code_id'], ['item_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_card_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_card_id', sa.UUID(), nullable=False),
    sa.Column('proposed_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='amendment_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_card_amendments')
    op.drop_table('rate_cards')
    op.drop_table('billing_milestones')
    op.drop_table('agreement_item_codes')
    op.drop_table('agreements')
    op.drop_table('agreement_code_sequences')
    # ### end Alembic commands ###
