"""phase 4b payment recording

Revision ID: a66431538f2b
Revises: 506543d9852b
Create Date: 2026-08-10 11:41:16.160652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66431538f2b'
down_revision: Union[str, None] = '506543d9852b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extend invoice_status with Phase 4B's terminal "Paid" state. Same .name-style
    # uppercase convention as Phase 4A's migration (506543d9852b) — SQLAlchemy's Enum
    # type here stores the Python member NAME as the native Postgres label, not .value.
    op.execute("ALTER TYPE invoice_status ADD VALUE IF NOT EXISTS 'PAID'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tds_section', sa.String(), nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('NEFT', 'RTGS', 'IMPS', 'UPI', 'CHEQUE', name='payment_mode'), nullable=False),
    sa.Column('company_bank_account', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('utr_reference', sa.String(), nullable=False),
    sa.Column('itc_eligible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('MAKER_RECORDED', 'CHECKER_CONFIRMED', 'REJECTED', name='payment_status'), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('late_payment_interest_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_override_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('original_section', sa.String(), nullable=False),
    sa.Column('original_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('new_section', sa.String(), nullable=False),
    sa.Column('new_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('payment_due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_due_date')
    op.drop_table('tds_override_log')
    op.drop_table('payments')
    op.drop_table('settings')
    # ### end Alembic commands ###

    # Note: the invoice_status 'PAID' label added in upgrade() is NOT removed here —
    # Postgres has no ALTER TYPE ... DROP VALUE (see 506543d9852b for the same note).
