"""phase 3a budget purchase orders grn

Revision ID: aa77c7b4ba79
Revises: db0c0c6d0b6f
Create Date: 2026-08-01 00:44:22.456094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa77c7b4ba79'
down_revision: Union[str, None] = 'db0c0c6d0b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_heads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('cost_centre', sa.String(), nullable=False),
    sa.Column('period_type', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='budget_period_type'), nullable=False),
    sa.Column('period_label', sa.String(), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('po_code_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('item_code_id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate_override_reason', sa.Text(), nullable=True),
    sa.Column('po_value_excl_gst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_po_value_incl_gst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('budget_head_id', sa.UUID(), nullable=False),
    sa.Column('delivery_completion_date', sa.Date(), nullable=False),
    sa.Column('po_validity_date', sa.Date(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'VENDOR_ACKNOWLEDGED', 'REJECTED', 'CANCELLED', 'LAPSED', 'CLOSED', name='purchase_order_status'), nullable=False),
    sa.Column('vendor_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('over_budget_justification', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['budget_head_id'], ['budget_heads.id'], ),
    sa.ForeignKeyConstraint(['item_code_id'], ['item_codes.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('budget_commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_head_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_head_id'], ['budget_heads.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_scn',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('GRN', 'SCN', name='grn_scn_type'), nullable=False),
    sa.Column('quantity_confirmed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('po_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('previous_delivery_date', sa.Date(), nullable=False),
    sa.Column('new_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_delivery_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='po_amendment_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('po_amendments')
    op.drop_table('grn_scn')
    op.drop_table('budget_commitments')
    op.drop_table('purchase_orders')
    op.drop_table('po_code_sequences')
    op.drop_table('budget_heads')
    # ### end Alembic commands ###
