"""phase 2b vendor portal kyc bank change notifications

Revision ID: db0c0c6d0b6f
Revises: 971b18378cdb
Create Date: 2026-07-24 17:28:53.348369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0c0c6d0b6f'
down_revision: Union[str, None] = '971b18378cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', name='otp_purpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('new_account_no', sa.String(), nullable=False),
    sa.Column('new_ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('status', sa.Enum('PENDING_FIRST_APPROVAL', 'PENDING_SECOND_APPROVAL', 'APPROVED', 'REJECTED', name='bank_change_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('first_approved_by', sa.UUID(), nullable=True),
    sa.Column('second_approved_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_kyc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'GST_CERTIFICATE', 'MSME_CERTIFICATE', 'BANK_PROOF', 'MOA_INCORPORATION', 'BENEFICIAL_OWNERSHIP', 'ITR_AUDITED_FINANCIALS', name='kyc_document_type'), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='kyc_document_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('linked_vendor_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key('fk_users_linked_vendor_id', 'users', 'vendors', ['linked_vendor_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_linked_vendor_id', 'users', type_='foreignkey')
    op.drop_column('users', 'session_version')
    op.drop_column('users', 'linked_vendor_id')
    op.drop_table('vendor_kyc_documents')
    op.drop_table('bank_change_requests')
    op.drop_table('vendor_otp_codes')
    op.drop_table('notifications')
    # ### end Alembic commands ###
